Add testing to update atomic habit
AY2223S2-CS2113-T12-4/tp pull request #64
Opened 2023-03-13 13:34 UTC by BernardLesley

Add JUnit testing for Update Atomic Habit

2023-03-13 17:18 UTC, wenxin-c reviewed
Overall good work, just some suggestions on coding style and naming conventions. Might need help from the rest for the naming convention comments as I'm not too sure as well. Other than that it looks good to me:D

2023-03-13 17:26 UTC, YongbinWang commented on src/main/java/seedu/duke/atomichabit/feature/AtomicHabit.java
> +    public void setCount(int increment) {
`increaseCount` will be more intuitive.

2023-03-13 17:27 UTC, nichyjt requested changes
Minor nits, please work on Wenxin's comments as well as mine and it LGTM!

2023-03-13 17:27 UTC, nichyjt commented on src/main/java/seedu/duke/atomichabit/feature/AtomicHabit.java
> +    public void setCount(int increment) {
I agree with Wen Xin, `increaseCount` may be more descriptive.

2023-03-13 17:27 UTC, nichyjt commented on src/test/java/seedu/duke/atomichabit/AtomicHabitTest.java
> +    }
A nit, but for fuller coverage, test if negative values throw the appropriate error as well

2023-03-13 19:54 UTC, BernardLesley commented
This fixes #67

2023-03-14 10:35 UTC, nichyjt approved these changes
Thanks for the fixes. LGTM!

2023-03-14 10:36 UTC, merged