Basic user command logic
AY2223S2-CS2113-T12-4/tp pull request #65
Opened 2023-03-13 16:32 UTC by haoyangw

Implement a very basic `MainManager` class using the newly introduced `Manager` interface to support reading and processing of users' commands. 

This is **very** basic, another PR shall integrate other features and make `WellNus` a properly working application. 

Feature developers, refer to the `MainManager` class for a sample implementation of `Manager` logic.

2023-03-13 18:13 UTC, wenxin-c requested changes
May I check is the ```executeCommands``` class for ```MainManager``` still being worked on? There isn't any code to swtich to other features like atomic habit. Maybe should use attibutes more instead of keep calling method? The rest are just minor suggestions and overall is good.

2023-03-13 18:13 UTC, wenxin-c commented on src/main/java/wellnus/common/MainManager.java
> +    private void executeCommands() {
You might want to add comments for this method to briefly introduce what it is doing since it is a main functionality for this class.

2023-03-14 02:04 UTC, nichyjt commented on src/main/java/wellnus/common/MainManager.java
> +        //     when all Command subclasses are defined
This is autoformatter in action?

2023-03-14 03:19 UTC, haoyangw commented on src/main/java/wellnus/common/MainManager.java
> +        //     when all Command subclasses are defined
> should we leave 4 spaces before 'when'

JavaDoc need, so I just followed the same. I actually don't know if there's a convention for pure (non-JavaDoc) multiline comments

2023-03-14 03:21 UTC, haoyangw commented on src/main/java/wellnus/common/MainManager.java
> +        //     when all Command subclasses are defined
> This is autoformatter in action?

No, I formatted manually by habit

2023-03-14 03:22 UTC, haoyangw commented on src/main/java/wellnus/WellNus.java
> +        this.getTextUi().printOutputMessage(WellNus.BYE_MESSAGE);
> May I check is the `executeCommands` class for `MainManager` still being worked on?

Yes, but not in this PR. There's a parallel PR being worked on for integrating other features which is more appropriate. Easier to review 2 separate PRs than one long PR in my opinion

2023-03-14 03:24 UTC, haoyangw commented on src/main/java/wellnus/common/MainManager.java
> +                if (featureManager.isEmpty() && !this.isSupportedCommand(featureKeyword)) {
Hmm `&&` is intentional, this condition basically means a keyword(e.g. `test`) is none of the known feature's keywords and also not a recognised 'main' command(e.g. `help`), so it's an invalid command(throw `BadCommandException`). Does that make sense?

2023-03-14 05:07 UTC, nichyjt reviewed
Some nits and comments. But everything seems ready to be merged once the kinks are ironed out!

2023-03-14 05:07 UTC, nichyjt commented on src/main/java/wellnus/common/MainManager.java
> +     */
The throw is not in the method signature

2023-03-14 05:07 UTC, nichyjt commented on src/main/java/wellnus/common/MainManager.java
> +    protected void setSupportedFeatureManagers() {
#68 merge will remove the need for @Override tag

2023-03-14 05:43 UTC, haoyangw commented on src/main/java/wellnus/common/MainManager.java
> +    }
Yeah, in the future I'll need to call other feature managers to build a multiline `String` in getFullDescription(), while getLongAppDescription() doesn't include feature descriptions, it's just an overall detailed description of WellNUS++.

I'll add a comment to make this clear

2023-03-14 10:32 UTC, nichyjt approved these changes
LGTM!

2023-03-14 10:54 UTC, wenxin-c approved these changes
LGTM!!

2023-03-14 14:50 UTC, nichyjt approved these changes
Thanks for the hard work after all the back and forth! 💪🏼 

LGTM!

2023-03-14 14:51 UTC, merged